# !! This file is automatically generated by: writer.py
#     date: 2025-08-25T18:07:24.498194+00:00

from enum import Enum


class ClassificationType(Enum):
    """
    Automatically generated Enum for ClassificationType
    """
    GEOGRAPHY = 1  # (Geography) {'classificationTypeFr': 'Géographie'}
    HFCE = 10  # {'classificationTypeFr': 'DCFM'}
    HS_6_DIGIT_LEVEL = 11  # (HS 6-digit level) {'classificationTypeFr': 'SH niveau 6'}
    IOIC2011LINK1961 = 12  # (IOIC2011Link1961) {'classificationTypeFr': 'CIES2011lien1961'}
    IOIC2011LINK1997 = 13  # (IOIC2011Link1997) {'classificationTypeFr': 'CIES2011lien1997'}
    LFSSPEC = 14  # {'classificationTypeFr': 'EPASPEC'}
    LFSSPEC2007 = 15  # {'classificationTypeFr': 'EPASPEC2007'}
    NAICS1997 = 16  # {'classificationTypeFr': 'SCIAN1997'}
    NAICS2002 = 17  # {'classificationTypeFr': 'SCIAN2002'}
    NAICS2007 = 18  # {'classificationTypeFr': 'SCIAN2007'}
    NAICS2012 = 19  # {'classificationTypeFr': 'SCIAN2012'}
    CATEGORY = 2  # (Category) {'classificationTypeFr': 'Catégorie'}
    NAPCS = 20  # {'classificationTypeFr': 'SCPAN'}
    NAPCS_V = 21  # {'classificationTypeFr': 'SCPAN_V'}
    NAPCS2012 = 22  # {'classificationTypeFr': 'SCPAN2012'}
    NOCS2001 = 23  # {'classificationTypeFr': 'CNPS2001'}
    NOCS2006 = 24  # {'classificationTypeFr': 'CNPS2006'}
    RETTRDSPEC = 25  # {'classificationTypeFr': 'COMDETSPEC'}
    RETTRDSPEC6 = 26  # {'classificationTypeFr': 'COMDETSPEC6'}
    SCCAI2011 = 27  # {'classificationTypeFr': 'CTPZI2011'}
    SCG = 28  # {'classificationTypeFr': 'CTB'}
    SIC1980E = 29  # {'classificationTypeFr': 'CTI1980E'}
    COMMODITY = 3  # (Commodity) {'classificationTypeFr': 'Produit'}
    SIC_1960 = 30  # (Standard Industrial Classification, 1960 (SIC)) {'classificationTypeFr': "Classification type d'industries, 1960 (CTI)"}
    SIC_1970 = 31  # (Standard Industrial Classification, 1970 (SIC)) {'classificationTypeFr': 'Classification type des industries, 1970 (CTI)'}
    VIOLATIONS = 32  # (Violations) {'classificationTypeFr': 'Infractions'}
    WHLSTRDSPEC = 33  # {'classificationTypeFr': 'COMGROSSPEC'}
    WHO_ICD_0_2= 34  # (World Health Organization, International Classification of Diseases for Oncology, Second Edition (ICD-O-2)) {'classificationTypeFr': "Organisation mondiale de la santé, Classification internationale des maladies pour l'oncologie, Deuxième édition (CIM-O-2)"}
    WHO_ICD_O_3 = 35  # (World Health Organization, International Classification of Diseases for Oncology, Third Edition (ICD-O-3)) {'classificationTypeFr': "Organisation mondiale de la santé, Classification internationale des maladies pour l'oncologie, Troisième édition (CIM-O-3)"}
    WHO_ICD_9 = 36  # (World Health Organization, International Classification of Diseases, Ninth Revision (ICD-9)) {'classificationTypeFr': 'Organisation mondiale de la santé, Classification internationale des maladies, Neuvième révision (CIM-9)'}
    WHO_ICD_10 = 37  # (World Health Organization, International Statistical Classification of Diseases and Related Health Problems, Tenth Revision (ICD-10)) {'classificationTypeFr': 'Organisation mondiale de la santé, Classification statistique internationale des maladies et des problèmes de santé connexes, Dixième révision (CIM-10)'}
    NOCS2011 = 38  # {'classificationTypeFr': 'CNP2011'}
    LFSSPEC2012 = 39  # {'classificationTypeFr': 'EPASPEC2012'}
    INDUSTRY = 4  # (Industry) {'classificationTypeFr': 'Industrie'}
    PRODUCT = 40  # (Product) {'classificationTypeFr': 'Produit'}
    NAPCS2017CPPI = 41  # {'classificationTypeFr': 'SCPAN2017IPOP'}
    NAICS2017 = 42  # {'classificationTypeFr': 'SCIAN2017'}
    SDAC2003 = 43  # {'classificationTypeFr': 'CTAD2003'}
    NAPCS2017 = 44  # {'classificationTypeFr': 'SCPAN2017'}
    BEC4 = 45  # {'classificationTypeFr': 'GCE4'}
    HEALTH_REGIONS_2015 = 46  # (Health regions 2015) {'classificationTypeFr': 'Régions sociosanitaires de 2015'}
    HEALTH_REGIONS_2017 = 47  # (Health regions 2017) {'classificationTypeFr': 'Régions sociosanitaires de 2017'}
    NOC2016 = 48  # {'classificationTypeFr': 'CNP2016'}
    WORLD_HEALTH_ORGANIZATION_INTERNATIONAL_STATISTICAL_CLASSIFICATION_OF_DISEASES_AND_RELATED_HEALTH_PROBLEMS_NINTH_REVISION_ICD_9_AND_TENTH_REVISION_ICD_10 = 49  # (World Health Organization, International Statistical Classification of Diseases and Related Health Problems, Ninth Revision (ICD-9) and Tenth Revision (ICD-10)) {'classificationTypeFr': 'Organisation mondiale de la Santé, Classification statistique internationale des maladies et des problèmes de santé connexes, Neuvième révision (CIM-9) et Dixième révision (CIM-10)'}
    BUSINESS_SECTOR_INDUSTRIES = 5  # (Business sector industries) {'classificationTypeFr': 'Les industries du secteur des entreprises'}
    CIP2016VAR = 50  # {'classificationTypeFr': 'CPE2016VAR'}
    NAICS2017V2 = 51  # (NAICS2017v2) {'classificationTypeFr': 'SCIAN2017v2'}
    CIP2016VARPG = 52  # {'classificationTypeFr': 'CPE2016VARRP'}
    SCCAI2016 = 53  # {'classificationTypeFr': 'CTPZI2016'}
    CIP2016VARSTEMANDBHASE = 54  # (CIP2016VARSTEMandBHASE) {'classificationTypeFr': 'CPE2016VARSTGMetSACHES'}
    SCCAI2017 = 55  # {'classificationTypeFr': 'CTPZI2017'}
    BEC5 = 56  # {'classificationTypeFr': 'GCE5'}
    IOIC2016LINK1961 = 57  # (IOIC2016Link1961) {'classificationTypeFr': 'CIES2016lien1961'}
    GENDER2018 = 58  # (Gender2018) {'classificationTypeFr': 'Genre2018'}
    MINORITY2015 = 59  # (Minority2015) {'classificationTypeFr': 'Minortié2015'}
    CCOFOG2014 = 6  # {'classificationTypeFr': 'CCFAPC2014'}
    CAI2015 = 60  # {'classificationTypeFr': 'CIA2015'}
    SCTG1996 = 61  # {'classificationTypeFr': 'CTBT1996'}
    IOIC2016SUMMARY = 62  # (IOIC2016Summary) {'classificationTypeFr': 'CIES2016Sommaire'}
    CAVAR1 = 63  # {'classificationTypeFr': 'CAVAR1'}
    CFOLS = 64  # {'classificationTypeFr': 'CPLOP'}
    NAICS2017V3 = 65  # (NAICS2017v3) {'classificationTypeFr': 'SCIAN2017v3'}
    SCCAI2018 = 66  # {'classificationTypeFr': 'CTPZI2018'}
    SCCAIV2018 = 67  # {'classificationTypeFr': 'CTPZIV2018'}
    CIP2016VCANNABIS = 68  # (CIP2016VCannabis) {'classificationTypeFr': 'CPE2016VCannabis'}
    CIP2016VCANNABISPRIMARY = 69  # (CIP2016VCannabisPrimary) {'classificationTypeFr': 'CPE2016VCannabisPrincipaux'}
    CGFS2014 = 7  # {'classificationTypeFr': 'SFPC2014'}
    CIP2016VARCANNABISSTEMANDBHASE = 70  # (CIP2016VARCannabisSTEMandBHASE) {'classificationTypeFr': 'CPE2016VARCannabisSTGMetSACHES'}
    LFSSPEC2017 = 71  # {'classificationTypeFr': 'EPASPEC2017'}
    HS_4_DIGIT_LEVEL = 72  # (HS 4-digit level) {'classificationTypeFr': 'HS niveau 4'}
    SCCAI2019 = 73  # {'classificationTypeFr': 'CTPZI2019'}
    NAICS2022 = 74  # {'classificationTypeFr': 'SCIAN2022'}
    NAPCS2022 = 75  # {'classificationTypeFr': 'SCPAN2022'}
    LFSNOC2021 = 76  # {'classificationTypeFr': 'EPACNP2021'}
    ICNPO = 77  # {'classificationTypeFr': 'CIOSBL'}
    NAICS = 78  # {'classificationTypeFr': 'SCIAN'}
    NOC2021 = 79  # {'classificationTypeFr': 'CNP2021'}
    CIP2000SPEC = 8  # {'classificationTypeFr': 'CPE2000SPEC'}
    CIP2021VARPG = 80  # {'classificationTypeFr': 'CPE2021VARRP'}
    CIP2021VARSTEMANDBHASE = 81  # (CIP2021VARSTEMandBHASE) {'classificationTypeFr': 'CPE2021VARSTIMetSACHES'}
    NAICS2022V1 = 82  # (NAICS2022v1) {'classificationTypeFr': 'SCIAN2022v1'}
    CIP2021VCANNABISPRIMARY = 83  # (CIP2021VCannabisPrimary) {'classificationTypeFr': 'CPE2021VCannabisPrincipaux'}
    CIP2021VARCANNABISSTEMANDBHASE = 84  # (CIP2021VARCannabisSTEMandBHASE) {'classificationTypeFr': 'CPE2021VARCannabisSTIMetSACHES'}
    CIP2021VCANNABIS = 85  # (CIP2021VCannabis) {'classificationTypeFr': 'CPE2021VCannabis'}
    CIP2021 = 86  # {'classificationTypeFr': 'CPE2021'}
    SCCAI2022 = 87  # {'classificationTypeFr': 'CTPZI2022'}
    LFSSPEC2022 = 88  # {'classificationTypeFr': 'EPASPEC2022'}
    CIP2021VALTERNATIVE = 89  # (CIP2021VAlternative) {'classificationTypeFr': 'CPE2021VAlternatifs'}
    CIP2011SPEC = 9  # {'classificationTypeFr': 'CPE2011SPEC'}
    NULL = 90  # {'classificationTypeFr': 'NULL'}
