# !! This file is automatically generated by: enum_writer.py
#     date: 2025-09-20T01:45:35.708022+00:00

from enum import Enum


class ClassificationType(Enum):
    """
    Automatically generated Enum for ClassificationType
    """

    GEO = 1  # Geography  // Géographie
    HFCE = 10  # HFCE  // DCFM
    HS_6_DGTL_LVL = 11  # HS 6-digit level  // SH niveau 6
    IOIC2011LINK1961 = 12  # IOIC2011Link1961  // CIES2011lien1961
    IOIC2011LINK1997 = 13  # IOIC2011Link1997  // CIES2011lien1997
    LFSSPEC = 14  # LFSSPEC  // EPASPEC
    LFSSPEC2007 = 15  # LFSSPEC2007  // EPASPEC2007
    NAICS1997 = 16  # NAICS1997  // SCIAN1997
    NAICS2002 = 17  # NAICS2002  // SCIAN2002
    NAICS2007 = 18  # NAICS2007  // SCIAN2007
    NAICS2012 = 19  # NAICS2012  // SCIAN2012
    CAT = 2  # Category  // Catégorie
    NAPCS = 20  # NAPCS  // SCPAN
    NAPCS_V = 21  # NAPCS_V  // SCPAN_V
    NAPCS2012 = 22  # NAPCS2012  // SCPAN2012
    NOCS2001 = 23  # NOCS2001  // CNPS2001
    NOCS2006 = 24  # NOCS2006  // CNPS2006
    RETTRDSPEC = 25  # RETTRDSPEC  // COMDETSPEC
    RETTRDSPEC6 = 26  # RETTRDSPEC6  // COMDETSPEC6
    SCCAI2011 = 27  # SCCAI2011  // CTPZI2011
    SCG = 28  # SCG  // CTB
    SIC1980E = 29  # SIC1980E  // CTI1980E
    COMM = 3  # Commodity  // Produit
    STD_IND_CLASS_1960 = 30  # Standard Industrial Classification, 1960 (SIC)  // Classification type d'industries, 1960 (CTI)
    STD_IND_CLASS_1970 = 31  # Standard Industrial Classification, 1970 (SIC)  // Classification type des industries, 1970 (CTI)
    VIOLATIONS = 32  # Violations  // Infractions
    WHLSTRDSPEC = 33  # WHLSTRDSPEC  // COMGROSSPEC
    WHO_ICD_FOR_ONCOLOGY_SEC_ED = 34  # World Health Organization, International Classification of Diseases for Oncology, Second Edition (ICD-O-2)  // Organisation mondiale de la santé, Classification internationale des maladies pour l'oncologie, Deuxième édition (CIM-O-2)
    WHO_ICD_FOR_ONCOLOGY_THIRD_ED = 35  # World Health Organization, International Classification of Diseases for Oncology, Third Edition (ICD-O-3)  // Organisation mondiale de la santé, Classification internationale des maladies pour l'oncologie, Troisième édition (CIM-O-3)
    WHO_ICD_NINTH_REVISION = 36  # World Health Organization, International Classification of Diseases, Ninth Revision (ICD-9)  // Organisation mondiale de la santé, Classification internationale des maladies, Neuvième révision (CIM-9)
    WHO_INTL_STAT_CLASS_OF_DISEASES_AND_REL_HLTH_PROB_TENTH_REVISION = 37  # World Health Organization, International Statistical Classification of Diseases and Related Health Problems, Tenth Revision (ICD-10)  // Organisation mondiale de la santé, Classification statistique internationale des maladies et des problèmes de santé connexes, Dixième révision (CIM-10)
    NOCS2011 = 38  # NOCS2011  // CNP2011
    LFSSPEC2012 = 39  # LFSSPEC2012  // EPASPEC2012
    IND = 4  # Industry  // Industrie
    PROD = 40  # Product  // Produit
    NAPCS2017CPPI = 41  # NAPCS2017CPPI  // SCPAN2017IPOP
    NAICS2017 = 42  # NAICS2017  // SCIAN2017
    SDAC2003 = 43  # SDAC2003  // CTAD2003
    NAPCS2017 = 44  # NAPCS2017  // SCPAN2017
    BEC4 = 45  # BEC4  // GCE4
    HLTH_REG_2015 = 46  # Health regions 2015  // Régions sociosanitaires de 2015
    HLTH_REG_2017 = 47  # Health regions 2017  // Régions sociosanitaires de 2017
    NOC2016 = 48  # NOC2016  // CNP2016
    WHO_INTL_STAT_CLASS_OF_DISEASES_AND_REL_HLTH_PROB_NINTH_REVISION = 49  # World Health Organization, International Statistical Classification of Diseases and Related Health Problems, Ninth Revision (ICD-9) and Tenth Revision (ICD-10)  // Organisation mondiale de la Santé, Classification statistique internationale des maladies et des problèmes de santé connexes, Neuvième révision (CIM-9) et Dixième révision (CIM-10)
    BUS_SECT_IND = (
        5  # Business sector industries  // Les industries du secteur des entreprises
    )
    CIP2016VAR = 50  # CIP2016VAR  // CPE2016VAR
    NAICS2017V2 = 51  # NAICS2017v2  // SCIAN2017v2
    CIP2016VARPG = 52  # CIP2016VARPG  // CPE2016VARRP
    SCCAI2016 = 53  # SCCAI2016  // CTPZI2016
    CIP2016VARSTEMANDBHASE = 54  # CIP2016VARSTEMandBHASE  // CPE2016VARSTGMetSACHES
    SCCAI2017 = 55  # SCCAI2017  // CTPZI2017
    BEC5 = 56  # BEC5  // GCE5
    IOIC2016LINK1961 = 57  # IOIC2016Link1961  // CIES2016lien1961
    GENDER2018 = 58  # Gender2018  // Genre2018
    MINORITY2015 = 59  # Minority2015  // Minortié2015
    CCOFOG2014 = 6  # CCOFOG2014  // CCFAPC2014
    CAI2015 = 60  # CAI2015  // CIA2015
    SCTG1996 = 61  # SCTG1996  // CTBT1996
    IOIC2016SUMMARY = 62  # IOIC2016Summary  // CIES2016Sommaire
    CAVAR1 = 63  # CAVAR1  // CAVAR1
    CFOLS = 64  # CFOLS  // CPLOP
    NAICS2017V3 = 65  # NAICS2017v3  // SCIAN2017v3
    SCCAI2018 = 66  # SCCAI2018  // CTPZI2018
    SCCAIV2018 = 67  # SCCAIV2018  // CTPZIV2018
    CIP2016VCANNABIS = 68  # CIP2016VCannabis  // CPE2016VCannabis
    CIP2016VCANNABISPRIMARY = (
        69  # CIP2016VCannabisPrimary  // CPE2016VCannabisPrincipaux
    )
    CGFS2014 = 7  # CGFS2014  // SFPC2014
    CIP2016VARCANNABISSTEMANDBHASE = (
        70  # CIP2016VARCannabisSTEMandBHASE  // CPE2016VARCannabisSTGMetSACHES
    )
    LFSSPEC2017 = 71  # LFSSPEC2017  // EPASPEC2017
    HS_4_DGTL_LVL = 72  # HS 4-digit level  // HS niveau 4
    SCCAI2019 = 73  # SCCAI2019  // CTPZI2019
    NAICS2022 = 74  # NAICS2022  // SCIAN2022
    NAPCS2022 = 75  # NAPCS2022  // SCPAN2022
    LFSNOC2021 = 76  # LFSNOC2021  // EPACNP2021
    ICNPO = 77  # ICNPO  // CIOSBL
    NAICS = 78  # NAICS  // SCIAN
    NOC2021 = 79  # NOC2021  // CNP2021
    CIP2000SPEC = 8  # CIP2000SPEC  // CPE2000SPEC
    CIP2021VARPG = 80  # CIP2021VARPG  // CPE2021VARRP
    CIP2021VARSTEMANDBHASE = 81  # CIP2021VARSTEMandBHASE  // CPE2021VARSTIMetSACHES
    NAICS2022V1 = 82  # NAICS2022v1  // SCIAN2022v1
    CIP2021VCANNABISPRIMARY = (
        83  # CIP2021VCannabisPrimary  // CPE2021VCannabisPrincipaux
    )
    CIP2021VARCANNABISSTEMANDBHASE = (
        84  # CIP2021VARCannabisSTEMandBHASE  // CPE2021VARCannabisSTIMetSACHES
    )
    CIP2021VCANNABIS = 85  # CIP2021VCannabis  // CPE2021VCannabis
    CIP2021 = 86  # CIP2021  // CPE2021
    SCCAI2022 = 87  # SCCAI2022  // CTPZI2022
    LFSSPEC2022 = 88  # LFSSPEC2022  // EPASPEC2022
    CIP2021VALTERNATIVE = 89  # CIP2021VAlternative  // CPE2021VAlternatifs
    CIP2011SPEC = 9  # CIP2011SPEC  // CPE2011SPEC
    NULL = 90  # NULL  // NULL
