# !! This file is automatically generated by: writer.py
#     date: 2025-08-25T18:07:23.004917+00:00

from enum import Enum


class Frequency(Enum):
    """
    Automatically generated Enum for Frequency
    """
    DAILY = 1  # (Daily) {'frequencyDescFr': 'Quotidienne'}
    SEMI_ANNUAL = 11  # (Semi-annual) {'frequencyDescFr': 'Semestrielle'}
    ANNUAL = 12  # (Annual) {'frequencyDescFr': 'Annuelle'}
    EVERY_2_YEARS = 13  # (Every 2 years) {'frequencyDescFr': 'Aux 2 ans'}
    EVERY_3_YEARS = 14  # (Every 3 years) {'frequencyDescFr': 'Aux 3 ans'}
    EVERY_4_YEARS = 15  # (Every 4 years) {'frequencyDescFr': 'Aux 4 ans'}
    EVERY_5_YEARS = 16  # (Every 5 years) {'frequencyDescFr': 'Aux 5 ans'}
    EVERY_10_YEARS = 17  # (Every 10 years) {'frequencyDescFr': 'Aux 10 ans'}
    OCCASIONAL = 18  # (Occasional) {'frequencyDescFr': 'Occasionnelle'}
    OCCASIONAL_QUARTERLY = 19  # (Occasional Quarterly) {'frequencyDescFr': 'Occasionnelle trimestrielle'}
    WEEKLY = 2  # (Weekly) {'frequencyDescFr': 'Hebdomadaire'}
    OCCASIONAL_MONTHLY = 20  # (Occasional Monthly) {'frequencyDescFr': 'Occasionnelle mensuelle'}
    OCCASIONAL_DAILY = 21  # (Occasional Daily) {'frequencyDescFr': 'Occasionnelle quotidienne'}
    BIWEEKLY = 4  # (Biweekly) {'frequencyDescFr': 'Aux 2 semaines'}
    MONTHLY = 6  # (Monthly) {'frequencyDescFr': 'Mensuelle'}
    BIMONTHLY = 7  # (Bimonthly) {'frequencyDescFr': 'Aux 2 mois'}
    QUARTERLY = 9  # (Quarterly) {'frequencyDescFr': 'Trimestrielle'}
