# !! This file is automatically generated by: writer.py
#     date: 2025-09-05T16:44:19.048583+00:00

from enum import Enum


class Frequency(Enum):
    """Statistics Canada Frequency codes"""

    DLY = 1  # (Daily) {'frequencyDescFr': 'Quotidienne'}
    SEMI_ANN = 11  # (Semi-annual) {'frequencyDescFr': 'Semestrielle'}
    ANN = 12  # (Annual) {'frequencyDescFr': 'Annuelle'}
    EVERY_2_YEARS = 13  # (Every 2 years) {'frequencyDescFr': 'Aux 2 ans'}
    EVERY_3_YEARS = 14  # (Every 3 years) {'frequencyDescFr': 'Aux 3 ans'}
    EVERY_4_YEARS = 15  # (Every 4 years) {'frequencyDescFr': 'Aux 4 ans'}
    EVERY_5_YEARS = 16  # (Every 5 years) {'frequencyDescFr': 'Aux 5 ans'}
    EVERY_10_YEARS = 17  # (Every 10 years) {'frequencyDescFr': 'Aux 10 ans'}
    OCCASIONAL = 18  # (Occasional) {'frequencyDescFr': 'Occasionnelle'}
    OCCASIONAL_QTR = 19  # (Occasional Quarterly) {'frequencyDescFr': 'Occasionnelle trimestrielle'}
    WKLY = 2  # (Weekly) {'frequencyDescFr': 'Hebdomadaire'}
    OCCASIONAL_MON = 20  # (Occasional Monthly) {'frequencyDescFr': 'Occasionnelle mensuelle'}
    OCCASIONAL_DLY = 21  # (Occasional Daily) {'frequencyDescFr': 'Occasionnelle quotidienne'}
    BIWEEKLY = 4  # (Biweekly) {'frequencyDescFr': 'Aux 2 semaines'}
    MON = 6  # (Monthly) {'frequencyDescFr': 'Mensuelle'}
    BIMONTHLY = 7  # (Bimonthly) {'frequencyDescFr': 'Aux 2 mois'}
    QTR = 9  # (Quarterly) {'frequencyDescFr': 'Trimestrielle'}


