# !! This file is automatically generated by: enum_writer.py
#     date: 2025-09-20T07:12:33.335081+00:00

from enum import Enum


class Frequency(Enum):
    """
    Automatically generated Enum for Frequency
    """
    DLY = 1  # Daily  // Quotidienne
    SEMI_ANN = 11  # Semi-annual  // Semestrielle
    ANN = 12  # Annual  // Annuelle
    EVERY_2_YR = 13  # Every 2 years  // Aux 2 ans
    EVERY_3_YR = 14  # Every 3 years  // Aux 3 ans
    EVERY_4_YR = 15  # Every 4 years  // Aux 4 ans
    EVERY_5_YR = 16  # Every 5 years  // Aux 5 ans
    EVERY_10_YR = 17  # Every 10 years  // Aux 10 ans
    OCCASIONAL = 18  # Occasional  // Occasionnelle
    OCCASIONAL_QTR = 19  # Occasional Quarterly  // Occasionnelle trimestrielle
    WKLY = 2  # Weekly  // Hebdomadaire
    OCCASIONAL_MON = 20  # Occasional Monthly  // Occasionnelle mensuelle
    OCCASIONAL_DLY = 21  # Occasional Daily  // Occasionnelle quotidienne
    BIWKLY = 4  # Biweekly  // Aux 2 semaines
    MON = 6  # Monthly  // Mensuelle
    BIOMON = 7  # Bimonthly  // Aux 2 mois
    QTR = 9  # Quarterly  // Trimestrielle

