# !! This file is automatically generated by: enum_writer.py
#     date: 2025-10-09T16:56:25.231786+00:00
"""Auto-generated enum module.

Generated from scalar data.
"""

from enum import Enum


class Scalar(Enum):
    """Automatically generated Enum for Scalar."""

    UNITS = 0  # units  // unités
    TENS = 1  # tens  // dizaines
    HUNDREDS = 2  # hundreds  // centaines
    THOUSANDS = 3  # thousands  // milliers
    TENS_OF_THOUSANDS = 4  # tens of thousands  // dizaines de milliers
    HUNDREDS_OF_THOUSANDS = 5  # hundreds of thousands  // centaines de milliers
    MILLIONS = 6  # millions  // millions
    TENS_OF_MILLIONS = 7  # tens of millions  // dizaines de millions
    HUNDREDS_OF_MILLIONS = 8  # hundreds of millions  // centaines de millions
    BILLIONS = 9  # billions  // milliards

