# !! This file is automatically generated by: writer.py
#     date: 2025-08-25T18:07:22.995335+00:00

from enum import Enum


class Scalar(Enum):
    """
    Automatically generated Enum for Scalar
    """
    UNITS = 0  # (units) {'scalarFactorDescFr': 'unités'}
    TENS = 1  # (tens) {'scalarFactorDescFr': 'dizaines'}
    HUNDREDS = 2  # (hundreds) {'scalarFactorDescFr': 'centaines'}
    THOUSANDS = 3  # (thousands) {'scalarFactorDescFr': 'milliers'}
    TENS_OF_THOUSANDS = 4  # (tens of thousands) {'scalarFactorDescFr': 'dizaines de milliers'}
    HUNDREDS_OF_THOUSANDS = 5  # (hundreds of thousands) {'scalarFactorDescFr': 'centaines de milliers'}
    MILLIONS = 6  # (millions) {'scalarFactorDescFr': 'millions'}
    TENS_OF_MILLIONS = 7  # (tens of millions) {'scalarFactorDescFr': 'dizaines de millions'}
    HUNDREDS_OF_MILLIONS = 8  # (hundreds of millions) {'scalarFactorDescFr': 'centaines de millions'}
    BILLIONS = 9  # (billions) {'scalarFactorDescFr': 'milliards'}
