# !! This file is automatically generated by: enum_writer.py
#     date: 2025-10-09T16:56:36.709808+00:00
"""Auto-generated enum module.

Generated from security_level data.
"""

from enum import Enum


class SecurityLevel(Enum):
    """Automatically generated Enum for SecurityLevel."""

    PUB = 0  # public  // public
    SUPPR = 1  # suppressed to meet the confidentiality requirements of the Statistics Act  // confidentiel en vertu des dispositions de la Loi sur la statistique

