# !! This file is automatically generated by: enum_writer.py
#     date: 2025-09-20T01:45:35.725592+00:00

from enum import Enum


class SecurityLevel(Enum):
    """
    Automatically generated Enum for SecurityLevel
    """

    PUB = 0  # public  // public
    SUPPR = 1  # suppressed to meet the confidentiality requirements of the Statistics Act  // confidentiel en vertu des dispositions de la Loi sur la statistique
