# !! This file is automatically generated by: writer.py
#     date: 2025-09-05T17:33:06.519590+00:00

from enum import Enum


class SecurityLevel(Enum):
    """Statistics Canada SecurityLevel codes"""

    PUB = 0  # (public) {'securityLevelRepresentationEn': None, 'securityLevelRepresentationFr': None, 'securityLevelDescFr': 'public'}
    SUPPRESSED_TO_MEET_THE_CONFIDENTIALITY_REQ_OF_THE_STAT_ACT = 1  # (suppressed to meet the confidentiality requirements of the Statistics Act) {'securityLevelRepresentationEn': 'x', 'securityLevelRepresentationFr': 'x', 'securityLevelDescFr': 'confidentiel en vert...
