# !! This file is automatically generated by: writer.py
#     date: 2025-09-05T16:44:20.334088+00:00

from enum import Enum


class Status(Enum):
    """Statistics Canada Status codes"""

    NORMAL = 0  # (normal) {'statusRepresentationEn': None, 'statusDescFr': 'normal', 'statusRepresentationFr': None}
    NOT_AVAILABLE_FOR_A_SPECIFIC_REFERENCE_PERIOD = 1  # (not available for a specific reference period) {'statusRepresentationEn': '..', 'statusDescFr': 'indisponible pour une période de référence précise', 'statusRepresentationFr': '..'}
    LESS_THAN_THE_LIMIT_OF_DETECTION = 10  # (less than the limit of detection) {'statusRepresentationEn': '<LOD', 'statusDescFr': 'inférieur à la limite de détection', 'statusRepresentationFr': '<LDD'}
    VAL_ROUNDED_TO_0 = 2  # (value rounded to 0 (zero) where there is a meaningful distinction between true zero and the value that was rounded) {'statusRepresentationEn': '0s', 'statusDescFr': 'valeur arrondie à 0 (zéro) là ...
    DATA_QUAL_EXCELLENT = 3  # (data quality: excellent) {'statusRepresentationEn': 'A', 'statusDescFr': 'qualité des données : excellente', 'statusRepresentationFr': 'A'}
    DATA_QUAL_VERY_GOOD = 4  # (data quality: very good) {'statusRepresentationEn': 'B', 'statusDescFr': 'qualité des données : très bonne', 'statusRepresentationFr': 'B'}
    DATA_QUAL_GOOD = 5  # (data quality: good) {'statusRepresentationEn': 'C', 'statusDescFr': 'qualité des données : bonne', 'statusRepresentationFr': 'C'}
    DATA_QUAL_ACCEPTABLE = 6  # (data quality: acceptable) {'statusRepresentationEn': 'D', 'statusDescFr': 'qualité des données : acceptable', 'statusRepresentationFr': 'D'}
    USE_WITH_CAUTION = 7  # (use with caution) {'statusRepresentationEn': 'E', 'statusDescFr': 'à utiliser avec prudence', 'statusRepresentationFr': 'E'}
    TOO_UNRELIABLE_TO_BE_PUBLISHED = 8  # (too unreliable to be published) {'statusRepresentationEn': 'F', 'statusDescFr': 'trop peu fiable pour être publié', 'statusRepresentationFr': 'F'}
    NOT_APPLICABLE = 9  # (not applicable) {'statusRepresentationEn': '...', 'statusDescFr': "n'ayant pas lieu de figurer", 'statusRepresentationFr': '...'}
