# !! This file is automatically generated by: enum_writer.py
#     date: 2025-10-09T16:56:25.329095+00:00
"""Auto-generated enum module.

Generated from symbol data.
"""

from enum import Enum


class Symbol(Enum):
    """Automatically generated Enum for Symbol."""

    NONE = 0  # none  // aucun
    PRELIM = 1  # preliminary  // provisoire
    REV = 3  # revised  // révisé

