# !! This file is automatically generated by: enum_writer.py
#     date: 2025-09-20T07:12:33.412184+00:00

from enum import Enum


class Symbol(Enum):
    """
    Automatically generated Enum for Symbol
    """

    NONE = 0  # none  // aucun
    PRELIM = 1  # preliminary  // provisoire
    REV = 3  # revised  // révisé
