# !! This file is automatically generated by: writer.py
#     date: 2025-09-05T16:44:19.230257+00:00

from enum import Enum


class Symbol(Enum):
    """Statistics Canada Symbol codes"""

    NONE = 0  # (none) {'symbolDescFr': 'aucun', 'symbolRepresentationEn': None, 'symbolRepresentationFr': None}
    PRELIM = 1  # (preliminary) {'symbolDescFr': 'provisoire', 'symbolRepresentationEn': 'p', 'symbolRepresentationFr': 'p'}
    REVISED = 3  # (revised) {'symbolDescFr': 'révisé', 'symbolRepresentationEn': 'r', 'symbolRepresentationFr': 'r'}
