# !! This file is automatically generated by: writer.py
#     date: 2025-09-05T17:33:06.665971+00:00

from enum import Enum


class Terminated(Enum):
    """Statistics Canada Terminated codes"""

    ACTIVE = 0  # (active) {'displayCodeEn': None, 'codeTextFr': 'actif', 'displayCodeFr': None}
    TERMINATED = 1  # (terminated) {'displayCodeEn': 't', 'codeTextFr': 'terminé', 'displayCodeFr': 't'}
