# !! This file is automatically generated by: enum_writer.py
#     date: 2025-09-20T07:13:50.459192+00:00

from enum import Enum


class Terminated(Enum):
    """
    Automatically generated Enum for Terminated
    """

    ACT = 0  # active  // actif
    TERMINATED = 1  # terminated  // terminé
