# !! This file is automatically generated by: enum_writer.py
#     date: 2025-10-09T16:56:36.718429+00:00
"""Auto-generated enum module.

Generated from terminated data.
"""

from enum import Enum


class Terminated(Enum):
    """Automatically generated Enum for Terminated."""

    ACT = 0  # active  // actif
    TERMINATED = 1  # terminated  // terminé

