# !! This file is automatically generated by: writer.py
#     date: 2025-09-05T17:33:07.233668+00:00

from enum import Enum


class WdsResponseStatus(Enum):
    """Statistics Canada WdsResponseStatus codes"""

    SUCCESS = 0  # (Success) {'codeTextFr': 'Succès'}
    INVALID_DATE = 1  # (Invalid date) {'codeTextFr': 'Date invalide'}
    INVALID_CUBE_AND_SERIES_COMBINATION = 2  # (Invalid cube and series combination) {'codeTextFr': 'Combinaison invalide de cube et de série'}
    REQUEST_FAILED = 3  # (Request failed) {'codeTextFr': 'La demande a échouée'}
    VECTOR_IS_INVALID = 4  # (Vector is invalid) {'codeTextFr': 'Vecteur invalide'}
    CUBE_PROD_ID_IS_INVALID = 5  # (Cube product id is invalid) {'codeTextFr': 'Identificateur du produit invalide'}
    CUBE_IS_CURRENTLY_BEING_PUBLISHED_PLEASE_TRY_AGAIN_LATER = 6  # (Cube is currently being published. Please try again later.) {'codeTextFr': 'Le cube est en cours de publication. Veuillez réessayer plus tard.'}
    CUBE_IS_NOT_AVAILABLE_FOR_MORE_INFO_CONTACT_US_TOLL_FREE_1_800_263_1136_514_283_8300_STATCAN_INFOSTATS_INFOSTATS_STATCANCAN_CA = 7  # (Cube is not available. For more information, contact us (toll-free 1-800-263-1136; 514-283-8300; STATCAN.infostats-infostats.STATCAN@canada.ca).) {'codeTextFr': "Le cube n'est pas disponible. Pour...
    INVALID_NUM_OF_REFERENCE_PERIODS = 8  # (Invalid number of reference periods) {'codeTextFr': 'Nombre de périodes de référence invalide.'}
