# !! This file is automatically generated by: enum_writer.py
#     date: 2025-10-09T16:56:36.771473+00:00
"""Auto-generated enum module.

Generated from wds_response_status data.
"""

from enum import Enum


class WdsResponseStatus(Enum):
    """Automatically generated Enum for WdsResponseStatus."""

    SUCCESS = 0  # Success  // Succès
    INVALID_DATE = 1  # Invalid date  // Date invalide
    INVALID_CUBE_AND_SERIES_COMBINATION = 2  # Invalid cube and series combination  // Combinaison invalide de cube et de série
    REQUEST_FAILED = 3  # Request failed  // La demande a échouée
    VECTOR_IS_INVALID = 4  # Vector is invalid  // Vecteur invalide
    CUBE_PROD_ID_IS_INVALID = 5  # Cube product id is invalid  // Identificateur du produit invalide
    CUBE_IS_CURRENTLY_BEING_PUB_PLEASE_TRY_AGAIN_LATER = 6  # Cube is currently being published. Please try again later.  // Le cube est en cours de publication. Veuillez réessayer plus tard.
    CUBE_IS_NOT_AVAIL_FOR_MORE_INFO_CONTACT_USTOLL_FREE_1_800_263_1136_514_283_8300_STATCAN_INFOSTATS_INFOSTATS_STATCANCAN_CA = 7  # Cube is not available. For more information, contact us (toll-free 1-800-263-1136; 514-283-8300; STATCAN.infostats-infostats.STATCAN@canada.ca). // Le cube n'est pas disponible. Pour plus d'information, contactez-nous sans frais 1-800-263-1136; 514-283-8300; STATCAN.infostats-infostats.STATCAN@canada.ca).
    INVALID_NUM_OF_REF_PERIOD = 8  # Invalid number of reference periods  // Nombre de périodes de référence invalide.

