# This file is automatically generated by ../build_info.py
__version__: str = '2025.10.10.171714'
__build_time__: str = '2025-10-10T17:17:14.982986+00:00'
__commit__: str = '419e0870fb6dc36b16a522d160be9b3aa63cd24e'
__branch__: str = 'feature/wds-client-docs-update'
