from datetime import datetime, timezone
from pathlib import Path
import build.__main__
import sys

from package_info import VERSION_FILE


def get_git_hash() -> str:
    '''
    Get the current git commit hash for HEAD.
    '''
    git_path = Path('.git')
    with (git_path / 'HEAD').open() as f:
        ref: str = f.read().strip().split(' ')[-1]
    with (git_path / ref).open() as f:
        commit_hash: str = f.read().strip()
    return commit_hash

def write_version() -> None:    
    """
    Write the version number and build metadata to a file.
    """
    version_time: datetime = datetime.now(tz=timezone.utc)
    version: str = f'{version_time.year}.{version_time.month}.{version_time.day}.{version_time.hour:02d}{version_time.minute:02d}{version_time.second:02d}'
    with open(file=VERSION_FILE, mode="w") as f:
        f.write(f"# This file is automatically generated by ../{Path(__file__).name} \n")
        f.write(f'__version__ = "{version}"\n')
        f.write(f'__build_time__ = "{version_time.isoformat()}"\n')
        f.write(f'__commit__: str = "{get_git_hash()}"\n')

if __name__ == "__main__":
    write_version()
    build.__main__.main(sys.argv[1:], 'python -m build')
    