# !! This file is automatically generated by: generate_enums.py
#     date: 2025-10-12T11:57:49.716703+00:00
"""Auto-generated enum module.

Generated from census_metropolitan_area data.
"""

from statscan.enums.geocode.pr_geocode import ProvinceGeoCode
from statscan.enums.schema import Schema


class CensusMetropolitanArea(ProvinceGeoCode):
    """Automatically generated Enum for CensusMetropolitanArea.

    Name: CMANAME_RMRNOM
    Value: CMAPUID_RMRPIDU
    Prefix: PREABBR_PRAABBREV
    """

    def __new__(
        cls,
        value: int,
        doc_en: str | None = None,
        doc_fr: str | None = None,
    ):
        """Create enum member with bilingual docstrings."""
        obj = object.__new__(cls)
        obj._value_ = value
        obj.__doc_en__ = doc_en
        obj.__doc_fr__ = doc_fr
        # Set __doc__ to English by default
        obj.__doc__ = doc_en
        return obj

    ALTA_CALGARY = 48825, "Calgary", "Calgary"
    ALTA_EDMONTON = 48835, "Edmonton", "Edmonton"
    ALTA_LETHBRIDGE = 48810, "Lethbridge", "Lethbridge"
    ALTA_RED_DEER = 48830, "Red Deer", "Red Deer"
    BC_ABBOTSFORD_MISSION = 59932, "Abbotsford - Mission", "Abbotsford - Mission"
    BC_CHILLIWACK = 59930, "Chilliwack", "Chilliwack"
    BC_KAMLOOPS = 59925, "Kamloops", "Kamloops"
    BC_KELOWNA = 59915, "Kelowna", "Kelowna"
    BC_NANAIMO = 59938, "Nanaimo", "Nanaimo"
    BC_VANCOUVER = 59933, "Vancouver", "Vancouver"
    BC_VICTORIA = 59935, "Victoria", "Victoria"
    MAN_WINNIPEG = 46602, "Winnipeg", "Winnipeg"
    NB_FREDERICTON = 13320, "Fredericton", "Fredericton"
    NB_MONCTON = 13305, "Moncton", "Moncton"
    NB_SAINT_JOHN = 13310, "Saint John", "Saint John"
    NL_ST_JOHNS = 10001, "St. John's", "St. John's"
    NS_HALIFAX = 12205, "Halifax", "Halifax"
    ONT_BARRIE = 35568, "Barrie", "Barrie"
    ONT_BELLEVILLE_QUINTE_WEST = 35522, "Belleville - Quinte West", "Belleville - Quinte West"
    ONT_BRANTFORD = 35543, "Brantford", "Brantford"
    ONT_GREATER_SUDBURY = 35580, "Greater Sudbury", "Grand Sudbury"
    ONT_GUELPH = 35550, "Guelph", "Guelph"
    ONT_HAMILTON = 35537, "Hamilton", "Hamilton"
    ONT_KINGSTON = 35521, "Kingston", "Kingston"
    ONT_KITCHENER_CAMBRIDGE_WATERLOO = 35541, "Kitchener - Cambridge - Waterloo", "Kitchener - Cambridge - Waterloo"
    ONT_LONDON = 35555, "London", "London"
    ONT_OSHAWA = 35532, "Oshawa", "Oshawa"
    ONT_OTTAWA_GATINEAU_ONTARIO_PART = 35505, "Ottawa - Gatineau (Ontario part", "partie de l'Ontario)"
    ONT_PETERBOROUGH = 35529, "Peterborough", "Peterborough"
    ONT_ST_CATHARINES_NIAGARA = 35539, "St. Catharines - Niagara", "St. Catharines - Niagara"
    ONT_THUNDER_BAY = 35595, "Thunder Bay", "Thunder Bay"
    ONT_TORONTO = 35535, "Toronto", "Toronto"
    ONT_WINDSOR = 35559, "Windsor", "Windsor"
    QUE_DRUMMONDVILLE = 24447, "Drummondville", "Drummondville"
    QUE_MONTRÉAL = 24462, "Montréal", "Montréal"
    QUE_OTTAWA_GATINEAU_PARTIE_DU_QUÉBEC = 24505, "Ottawa - Gatineau (partie du Québec", "Quebec part)"
    QUE_QUÉBEC = 24421, "Québec", "Québec"
    QUE_SAGUENAY = 24408, "Saguenay", "Saguenay"
    QUE_SHERBROOKE = 24433, "Sherbrooke", "Sherbrooke"
    QUE_TROIS_RIVIÈRES = 24442, "Trois-Rivières", "Trois-Rivières"
    SASK_REGINA = 47705, "Regina", "Regina"
    SASK_SASKATOON = 47725, "Saskatoon", "Saskatoon"

    @classmethod
    def get_schema(cls) -> Schema:
        """Return the Schema for this geo code type."""
        return Schema.CMA

    @classmethod
    def get_nchars(cls) -> int:
        """Return the number of characters in the code for this enum."""
        return 3
