# !! This file is automatically generated by: generate_enums.py
#     date: 2025-10-12T11:57:48.426305+00:00
"""Auto-generated enum module.

Generated from province_territory data.
"""

from statscan.enums.geocode.geocode import GeoCode
from statscan.enums.schema import Schema


class ProvinceTerritory(GeoCode):
    """Automatically generated Enum for ProvinceTerritory.

    Name: PRNAME_PRNOM
    Value: PRUID_PRIDU
    """

    def __new__(
        cls,
        value: int,
        doc_en: str | None = None,
        doc_fr: str | None = None,
    ):
        """Create enum member with bilingual docstrings."""
        obj = object.__new__(cls)
        obj._value_ = value
        obj.__doc_en__ = doc_en
        obj.__doc_fr__ = doc_fr
        # Set __doc__ to English by default
        obj.__doc__ = doc_en
        return obj

    ALBERTA = 48, "Alberta", "Alberta"
    BRITISH_COLUMBIA = 59, "British Columbia", "Colombie-Britannique"
    MANITOBA = 46, "Manitoba", "Manitoba"
    NEWFOUNDLAND_AND_LABRADOR = 10, "Newfoundland and Labrador", "Terre-Neuve-et-Labrador"
    NEW_BRUNSWICK = 13, "New Brunswick", "Nouveau-Brunswick"
    NORTHWEST_TERRITORIES = 61, "Northwest Territories", "Territoires du Nord-Ouest"
    NOVA_SCOTIA = 12, "Nova Scotia", "Nouvelle-Écosse"
    NUNAVUT = 62, "Nunavut", "Nunavut"
    ONTARIO = 35, "Ontario", "Ontario"
    PRINCE_EDWARD_ISLAND = 11, "Prince Edward Island", "Île-du-Prince-Édouard"
    QUEBEC = 24, "Quebec", "Québec"
    SASKATCHEWAN = 47, "Saskatchewan", "Saskatchewan"
    YUKON = 60, "Yukon", "Yukon"

    @classmethod
    def get_schema(cls) -> Schema:
        """Return the Schema for this geo code type."""
        return Schema.PR

    @classmethod
    def get_nchars(cls) -> int:
        """Return the number of characters in the code for this enum."""
        return 2
