"""
Some default abbreviation mappings for enum generation.

Note: 
    Many abbreviations are extended via morphogenic variants.
    Sensible root words can be tested with:
        tools.substitution.SubstitutionEngine._generate_variants_static()
    No sense in adding duplicates :)
"""

DEFAULT_ABBREVIATIONS = {
    # provinces
    "ab": ["alberta"],
    "bc": ["british columbia"],
    "mb": ["manitoba"],
    "nb": ["new brunswick"],
    "nl": ["newfoundland and labrador"],
    "ns": ["nova scotia"],
    "nt": ["northwest territories"],
    "nu": ["nunavut"],
    "on": ["ontario"],
    "pe": ["prince edward island"],
    "qc": ["quebec"],
    "sk": ["saskatchewan"],
    "yt": ["yukon"],
    # other places
    "usa": [
        "u.s.a.",
        "united states of america",
        "united states",
    ],
    # phrases and terms
    "cad": ["canadian dollars"],
    "copd": ["chronic obstructive pulmonary disease"],
    "gdp": ["gross domestic product"],
    "ghg": ["greenhouse gas"],
    "icd": ["international classification of diseases"],
    "na": ["not applicable"],
    "osb": ["oriented strandboard"],
    "ppe": ["personal protective equipment"],
    "real": ["real estate"],
    "suppr": ["suppressed to meet the confidentiality requirements of the statistics act"],
    "ui": ["user interface"],
    "ux": ["user experience"],
    "who": ["world health organization"],
    # all others (alphabetically sorted, duplicates removed)
    "abd": ["abroad"],
    "aborig": ["aboriginal"],
    "abs": ["absence"],
    "academ": ["academic"],
    "accept": ["accept"],
    "access": ["access"],
    "accom": ["accommodate"],
    "acct": ["account"],
    "act": [
        "active",
        "actual",
    ],
    "adapt": ["adapt"],
    "adj": ["adjust"],
    "admin": ["administer"],
    "adv": [
        "advertise",
        "advance",
        "adventure",
    ],
    "aero": ["aerospace"],
    "affl": ["affiliate"],
    "afford": [
        "afford",
        "affordability",
    ],
    "affr": ["affair"],
    "aggr": ["aggregate"],
    "agn": ["agent"],
    "agnc": ["agency"],
    "agric": ["agriculture"],
    "alc": ["alcohol"],
    "allow": ["allow"],
    "alt": ["alternative"],
    "anal": ["analytical"],
    "ann": [
        "annual",
        "annually",
    ],
    "app": ["apply"],
    "appl": ["appliance"],
    "appr": ["appraiser"],
    "apprtc": ["apprentice"],
    "apt": ["apartment"],
    "aquacult": ["aquaculture"],
    "arch": [
        "architect",
        "architectural",
    ],
    "arrg": ["arrange"],
    "art": ["art"],
    "assess": ["assess"],
    "asset": ["assets"],
    "assist": ["assist"],
    "assoc": ["associate"],
    "assur": ["assure"],
    "attr": ["attract"],
    "audit": ["audit"],
    "auth": [
        "authority",
        "authorities",
    ],
    "auto": ["automotive"],
    "avail": ["avail"],
    "avg": ["average"],
    "aware": ["aware"],
    "bal": ["balance"],
    "bank": ["banking"],
    "bcast": ["broadcast"],
    "behav": ["behaviour"],
    "bev": ["beverage"],
    "bft": ["benefit"],
    "biann": ["biannual"],
    "biling": [
        "bilingual",
        "bilingualism",
    ],
    "bio": ["biological"],
    "biodiv": ["biodiversity"],
    "biomon": ["bimonthly"],
    "bioprod": ["bioproduct"],
    "biotech": ["biotechnology"],
    "biwkly": ["biweekly"],
    "bldg": ["building"],
    "bus": ["business"],
    "can": [
        "canada",
        "canadian",
        "canada's",
    ],
    "cap": [
        "capital",
        "capacity",
    ],
    "cardio": ["cardiovascular"],
    "cat": ["category"],
    "cen": ["census"],
    "cert": [
        "certificate",
        "certification",
    ],
    "char": ["characteristic"],
    "charit": [
        "charity",
        "charitable",
    ],
    "chart": ["chartered"],
    "chem": ["chemical"],
    "child": ["child"],
    "chron": ["chronic"],
    "civ": ["civil"],
    "class": [
        "class",
        "classification",
    ],
    "clean": ["cleaning"],
    "clg": ["college"],
    "cli": ["client"],
    "cloth": ["clothing"],
    "comm": [
        "commercial",
        "commercialization",
        "commission",
        "commodity",
        "communicate",
        "commute",
        "community",
    ],
    "commun": ["communication"],
    "comp": [
        "comply",
        "company",
        "compare",
        "composite",
        "computer",
        "component",
        "competent",
        "compensate",
    ],
    "cond": ["condition"],
    "condo": ["condominium"],
    "cons": [
        "consolidate",
        "consumption",
        "consumer",
    ],
    "const": [
        "construct",
        "construction",
    ],
    "consult": ["consult"],
    "cont": [
        "continue",
        "content",
    ],
    "coord": ["coordinate"],
    "corp": ["corporate"],
    "correct": ["correction"],
    "cov": ["cover"],
    "cred": ["credit"],
    "crush": ["crush"],
    "ctrl": ["control"],
    "cult": ["culture"],
    "curr": ["current"],
    "cust": ["customer"],
    "dec": [
        "decorative",
        "december",
    ],
    "def": ["defence"],
    "deg": ["degrees"],
    "del": ["delivery"],
    "demo": [
        "demographic",
        "demography",
    ],
    "dent": ["dental"],
    "depr": [
        "depression",
        "deprivation",
        "depreciation",
    ],
    "dept": ["department"],
    "design": ["design"],
    "desk": ["desktop"],
    "dest": ["destination"],
    "detect": ["detection"],
    "dev": [
        "develop",
        "device",
    ],
    "dgtl": ["digital"],
    "diabl": ["disability"],
    "diff": ["differential"],
    "dipl": ["diploma"],
    "dir": ["directory"],
    "disc": [
        "discover",
        "discriminate",
    ],
    "discl": ["disclose"],
    "disp": ["dispose"],
    "displ": ["displace"],
    "dissem": ["disseminate"],
    "dist": ["distribute"],
    "div": [
        "division",
        "diverse",
    ],
    "dly": ["daily"],
    "doc": ["document"],
    "dom": ["domestic"],
    "dr": [
        "doctor",
        "doctorate",
    ],
    "drink": ["drink"],
    "dwel": ["dwell"],
    "dyn": ["dynamic"],
    "earn": ["earn"],
    "eco": ["ecosystem"],
    "econ": ["economy"],
    "ed": ["edition"],
    "edu": ["educational"],
    "elec": [
        "electric",
        "electrical",
        "electronic",
    ],
    "elem": ["elementary"],
    "emerg": ["emergency"],
    "emiss": ["emission"],
    "emo": ["emotion"],
    "employ": ["employ"],
    "en": ["english"],
    "enforce": ["enforce"],
    "eng": ["engineer"],
    "enrol": [
        "enroll",
        "enrolment",
    ],
    "ent": [
        "entertain",
        "enterprise",
        "entrepreneur",
        "entrepreneurship",
    ],
    "enterpr": ["enterprises"],
    "env": ["environment"],
    "epidem": [
        "epidemic",
        "epidemiological",
    ],
    "equip": ["equipment"],
    "est": [
        "estimate",
        "estimation",
    ],
    "establish": ["establish"],
    "ethno": ["ethnocultural"],
    "eval": ["evaluate"],
    "ex": ["exchange"],
    "excl": ["exclude"],
    "exec": ["execute"],
    "exp": [
        "expend",
        "expense",
        "experience",
        "expose",
    ],
    "expect": ["expect"],
    "ext": ["external"],
    "extract": ["extract"],
    "fab": ["fabricate"],
    "fac": [
        "facility",
        "factory",
    ],
    "fact": ["factor"],
    "fam": ["family"],
    "farm": ["farm"],
    "fed": ["federal"],
    "fgn": ["foreign"],
    "fin": ["finance"],
    "fish": ["fish"],
    "fit": ["fitness"],
    "food": ["food"],
    "forest": ["forest"],
    "fr": ["french"],
    "func": [
        "function",
        "functional",
    ],
    "furn": ["furniture"],
    "gas": ["gasoline"],
    "gen": [
        "generate",
        "general",
        "genetic",
    ],
    "geo": ["geography"],
    "geomat": ["geomatic"],
    "geospat": ["geospatial"],
    "glbl": [
        "global",
        "globalize",
    ],
    "gov": ["govern"],
    "grad": ["graduate"],
    "grp": ["group"],
    "guide": ["guideline"],
    "haz": ["hazard"],
    "her": ["heritage"],
    "hh": ["household"],
    "hist": ["history"],
    "hlth": [
        "health",
        "healthcare",
    ],
    "horticult": ["horticulture"],
    "hosp": ["hospitality"],
    "hw": ["hardware"],
    "id": ["identity"],
    "idx": ["index"],
    "immigr": ["immigrate"],
    "improv": ["improve"],
    "inc": ["income"],
    "incl": ["include"],
    "ind": [
        "independent",
        "individual",
        "indicate",
        "industry",
        "industrial",
    ],
    "indig": ["indigenous"],
    "ineq": ["inequality"],
    "inet": ["internet"],
    "infer": ["inference"],
    "info": ["information"],
    "infra": ["infrastructure"],
    "init": ["initiative"],
    "innov": [
        "innovation",
        "innovative",
    ],
    "ins": ["insurance"],
    "inst": [
        "install",
        "institution",
    ],
    "instit": ["institutions"],
    "instr": ["instruct"],
    "insul": ["insulate"],
    "int": ["integrate"],
    "intel": [
        "intellect",
        "intelligence",
    ],
    "intent": ["intention"],
    "intermed": ["intermediary"],
    "interp": ["interpret"],
    "intl": ["international"],
    "invent": ["inventory"],
    "invest": ["invest"],
    "invlv": ["involve"],
    "io": [
        "input-output",
        "input output",
    ],
    "iso": ["isolate"],
    "know": ["knowledge"],
    "lab": ["labour"],
    "lang": ["language"],
    "learn": ["learn"],
    "lease": ["lease"],
    "legal": ["legal"],
    "lend": ["lend"],
    "lg": ["large"],
    "liab": ["liability"],
    "lic": ["license"],
    "limit": ["limit"],
    "listen": ["listen"],
    "lit": ["literacy"],
    "liv": ["live"],
    "loan": ["loan"],
    "loc": ["local"],
    "log": ["logistic"],
    "long": ["longitude"],
    "lvl": ["level"],
    "mach": ["machine"],
    "maint": ["maintain"],
    "maj": ["major"],
    "manufact": ["manufacturing"],
    "map": ["map"],
    "mat": [
        "material",
        "maternal",
    ],
    "math": ["mathematic"],
    "meas": ["measure"],
    "mech": ["mechanical"],
    "med": [
        "medical",
        "medium",
    ],
    "media": ["media"],
    "merch": ["merchandise"],
    "meth": ["method"],
    "metro": ["metropolitan"],
    "mfg": ["manufacture"],
    "mgmt": ["management"],
    "mig": ["migrate"],
    "min": [
        "mining",
        "minority",
        "minimum",
    ],
    "miscond": ["misconduct"],
    "mkt": ["market"],
    "mng": ["manage"],
    "mob": ["mobile"],
    "mod": [
        "modify",
        "module",
    ],
    "mon": [
        "monitor",
        "monthly",
    ],
    "mort": [
        "mortal",
        "mortgage",
    ],
    "mot": ["motion"],
    "motiv": ["motivate"],
    "multinat": ["multinational"],
    "munic": ["municipal"],
    "mvmt": ["movement"],
    "nanotech": ["nanotechnology"],
    "nat": [
        "nature",
        "natural",
        "nation",
    ],
    "natl": ["national"],
    "net": ["network"],
    "neuro": ["neurological"],
    "num": ["number"],
    "nutr": [
        "nutrient",
        "nutrition",
    ],
    "occ": ["occupy"],
    "off": ["official"],
    "oper": ["operate"],
    "opport": ["opportune"],
    "org": [
        "organize",
        "organizational",
    ],
    "orient": [
        "orient",
        "orientation",
    ],
    "orig": ["origin"],
    "owner": ["owner"],
    "pass": ["passenger"],
    "pat": ["pattern"],
    "pens": ["pension"],
    "perc": ["perceive"],
    "perf": ["perform"],
    "period": ["period"],
    "periph": ["periphery"],
    "perm": ["permanent"],
    "pers": [
        "person",
        "personal",
        "personnel",
    ],
    "petro": ["petroleum"],
    "petrochem": ["petrochemical"],
    "pharm": ["pharmaceutical"],
    "phys": ["physical"],
    "pict": ["picture"],
    "pkg": ["package"],
    "plan": ["plan"],
    "plt": ["plant"],
    "pol": ["policy"],
    "pop": [
        "populate",
        "populaires",
    ],
    "port": ["portrait"],
    "pos": ["position"],
    "postsec": ["postsecondary"],
    "ppl": ["people"],
    "pr": ["public relation"],
    "pract": ["practice"],
    "preg": ["pregnant"],
    "prelim": ["preliminary"],
    "prep": ["preparedness"],
    "pres": ["pressure"],
    "prev": ["prevention"],
    "pri": ["primary"],
    "print": ["printing"],
    "prio": ["priorities"],
    "priv": [
        "private",
        "privacy",
    ],
    "prob": ["problem"],
    "proc": [
        "process",
        "procure",
        "procedure",
    ],
    "prod": [
        "product",
        "produce",
        "productive",
    ],
    "profess": [
        "profession",
        "professional",
    ],
    "prog": [
        "program",
        "programme",
    ],
    "proj": ["project"],
    "promo": [
        "promote",
        "promotor",
    ],
    "prop": ["property"],
    "prosec": ["prosecutorial"],
    "protect": ["protect"],
    "prov": [
        "province",
        "provide",
    ],
    "ptnr": ["partner"],
    "pub": [
        "public",
        "publish",
    ],
    "purch": ["purchase"],
    "pwr": ["power"],
    "qtr": ["quarter"],
    "qual": [
        "quality",
        "qualification",
    ],
    "quest": ["questionnaire"],
    "rec": [
        "record",
        "recreation",
    ],
    "reconcil": ["reconciliation"],
    "recov": ["recover"],
    "recpt": ["receipt"],
    "ref": [
        "refine",
        "reference",
    ],
    "reg": [
        "register",
        "regulate",
        "region",
    ],
    "regr": ["regress"],
    "rel": [
        "relate",
        "release",
    ],
    "relig": ["religion"],
    "remun": ["remunerate"],
    "reno": ["renovate"],
    "rent": ["rent"],
    "rep": [
        "repair",
        "report",
    ],
    "req": ["require"],
    "res": [
        "research",
        "resident",
        "residential",
        "resource",
    ],
    "resil": ["resilient"],
    "resp": ["respond"],
    "rest": ["restaurant"],
    "restric": ["restriction"],
    "ret": ["retail"],
    "retire": ["retire"],
    "rev": [
        "revenue",
        "revise",
    ],
    "rx": ["prescription"],
    "sal": ["salary"],
    "sat": ["satellite"],
    "sav": ["save"],
    "sched": ["schedule"],
    "sci": [
        "science",
        "scientific",
    ],
    "sec": [
        "second",
        "secondary",
        "security",
    ],
    "secret": ["secretariat"],
    "sect": ["sector"],
    "sel": ["select"],
    "semiann": [
        "semi-annually",
        "semiannually",
    ],
    "serv": ["serve"],
    "sex": ["sex"],
    "ship": ["ship"],
    "sm": ["small"],
    "soc": [
        "social",
        "society",
    ],
    "socecon": ["socioeconomic"],
    "soft": ["software"],
    "spec": [
        "specify",
        "special",
        "spectator",
    ],
    "spend": ["spend"],
    "sport": ["sport"],
    "src": ["source"],
    "stat": [
        "statistic",
        "statistical",
    ],
    "std": [
        "standard",
        "sexually transmitted disease",
    ],
    "stmnt": ["statement"],
    "stn": ["station"],
    "stor": ["store"],
    "strat": ["strategy"],
    "struct": [
        "structure",
        "structural",
    ],
    "sts": ["status"],
    "stud": ["student"],
    "subprov": ["subprovincial"],
    "subs": ["subsidiary"],
    "subst": ["substance"],
    "suff": ["suffice"],
    "supp": [
        "supply",
        "supplementary",
        "support",
    ],
    "surv": ["survey"],
    "svc": ["service"],
    "sys": ["system"],
    "tabl": [
        "table",
        "tablet",
    ],
    "tax": ["tax"],
    "tech": [
        "technical",
        "technology",
    ],
    "telecom": ["telecommunication"],
    "terr": ["territory"],
    "test": ["test"],
    "text": ["textile"],
    "theat": ["theatre"],
    "thera": ["therapeutic"],
    "therm": ["thermal"],
    "tot": ["total"],
    "tour": [
        "tour",
        "tourism",
    ],
    "track": ["track"],
    "train": ["train"],
    "transport": [
        "transaction",
        "transfer",
        "transit",
        "translate",
        "transmit",
        "transport",
        "transportation",
    ],
    "treasury": ["treasury"],
    "triann": [
        "triennial",
        "triannual",
    ],
    "truck": ["truck"],
    "trust": ["trust"],
    "trvl": ["travel"],
    "tv": ["television"],
    "unempl": ["unemployment"],
    "uni": ["university"],
    "union": [
        "union",
        "unionization",
    ],
    "util": ["utility"],
    "vacc": ["vaccinate"],
    "val": ["value"],
    "var": ["variable"],
    "veg": ["vegetable"],
    "vehic": ["vehicle"],
    "vend": ["vend"],
    "vet": [
        "veterinary",
        "veteran",
    ],
    "victim": [
        "victim",
        "victimization",
    ],
    "vid": ["video"],
    "voc": ["vocational"],
    "vol": [
        "volume",
        "volunteer",
    ],
    "vul": ["vulnerable"],
    "ware": ["warehouse"],
    "web": ["website"],
    "whole": ["wholesale"],
    "wkly": ["weekly"],
    "xmas": ["christmas"],
    "xsect": ["cross-sectional"],
    "yr": ["yearly"],
}
