# This file is automatically generated by ../build_script.py 
__version__ = "2025.6.9.182950"
__build_time__ = "2025-06-09T18:29:50.494949+00:00"
__commit__: str = "36af1c6c6a86f399ffb927573541653ccf68420b"
