# This file is automatically generated by ../package_info.py 
__version__: str = '2025.6.9.200229'
__build_time__: str = '2025-06-09T20:02:29.250951+00:00'
__commit__: str = '1c752d7595dc4285159825371898757e4cf35fe8'
