# This file is automatically generated by ../package_info.py 
__version__: str = '2025.9.20.153307'
__build_time__: str = '2025-09-20T15:33:07.593051+00:00'
__commit__: str = '0668d6333b842fe5a346ebe9b250f68c7aca1cee'
