"""
SDMX End-User Functionality Tests
=================================

Tests for SDMX functionality using fixture data.
SDMX is a secondary priority - mainly for legacy compatibility.

Key areas:
- SDMX response parsing
- Data structure validation
- Integration with existing SDMX workflows
- Error handling for SDMX data

Uses fixtures generated by test_network_fixtures.py
"""

import pytest
from statscan.sdmx.response import SDMXResponse


class TestSDMXParsing:
    """Test SDMX response parsing functionality."""
    
    def test_sdmx_model_import(self):
        """Test SDMX model can be imported."""
        assert SDMXResponse is not None
        print("✅ SDMXResponse model imported successfully")
    
    def test_parse_minimal_sdmx_fixture(self, sdmx_minimal_data):
        """Test parsing minimal SDMX fixture."""
        # Basic validation of fixture data
        assert sdmx_minimal_data is not None
        print(f"✅ SDMX minimal fixture loaded: {type(sdmx_minimal_data)}")
        
        # Test that we can work with the data structure
        if isinstance(sdmx_minimal_data, dict):
            print(f"📊 SDMX dict keys: {list(sdmx_minimal_data.keys())}")
        elif isinstance(sdmx_minimal_data, list):
            print(f"📋 SDMX list length: {len(sdmx_minimal_data)}")


class TestSDMXCompatibility:
    """Test SDMX compatibility and legacy support."""
    
    def test_sdmx_response_creation(self):
        """Test creating SDMXResponse instances."""
        # Test basic instantiation without data
        try:
            response = SDMXResponse()
            print("✅ SDMXResponse can be instantiated")
        except Exception as e:
            print(f"ℹ️  SDMXResponse requires initialization data: {e}")
    
    def test_sdmx_data_types(self, sdmx_minimal_data):
        """Test handling different SDMX data types."""
        # Validate that fixture provides usable data
        assert sdmx_minimal_data is not None
        
        # Test data structure compatibility
        if isinstance(sdmx_minimal_data, (dict, list)):
            print(f"✅ SDMX data type compatible: {type(sdmx_minimal_data)}")
        else:
            print(f"ℹ️  Unexpected SDMX data type: {type(sdmx_minimal_data)}")


class TestSDMXSimple:
    """Simple SDMX tests that don't require fixtures."""
    
    def test_sdmx_import_basic(self):
        """Test basic SDMX imports work."""
        from statscan.sdmx import response
        assert response is not None
        print("✅ SDMX module imports successfully")
