name: "PR Quality Checks"

on:
  pull_request:
    branches: [ "dev", "main" ]
    paths:
      # Only run on package changes (same filtering as changelog)
      - 'statscan/**'
      - 'pyproject.toml'
      - 'requirements*.txt'
      - 'setup.py'

jobs:
  quality-assurance:
    name: "Quality Assurance"
    uses: ./.github/workflows/qa-qc-checks.yml
    with:
      build-required: false  # PRs don't need build artifacts
      python-versions: '["3.11", "3.12"]'  # Faster testing for PRs
    secrets: inherit

  status-check:
    name: "PR Status Summary"
    runs-on: ubuntu-latest
    needs: quality-assurance  
    if: always()
    
    steps:
      - name: PR Quality Status
        run: |
          echo "🔍 PR Quality Checks Complete"
          echo "Status: ${{ needs.quality-assurance.result }}"
          
          if [[ "${{ needs.quality-assurance.result }}" == "success" ]]; then
            echo "✅ All quality checks passed - PR ready for review"
          else
            echo "❌ Quality checks failed - please review the issues above"
            exit 1
          fi
